

//App
export const CHANGE_APP_STATUS = "CHANGE_APP_STATUS";
export const CHANGE_LOADING = "CHANGE_LOADING";
export const CHANGE_APP_LANGUAGE = "CHANGE_APP_LANGUAGE";


//User
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_FOLLOWING_DATA = "SET_FOLLOWING_DATA";
export const SET_FAVOURITES_DATA = "SET_FAVOURITES_DATA";
export const SET_ACTIVE_USER_TYPE = "SET_ACTIVE_USER_TYPE";
export const SET_CHAT_DATA = "SET_CHAT_DATA";
export const UPDATE_CHAT_DATA = "UPDATE_CHAT_DATA";
export const SET_MY_REVIEWS = "SET_MY_REVIEWS";
export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const SET_PRODUCTS_WISHLIST = "SET_PRODUCTS_WISHLIST";
export const SET_APP_SETTINGS = "SET_APP_SETTINGS";


//Motor
export const LOGGED_USER_DETAILS = "LOGGED_USER_DETAILS";
export const QUICK_QUOTE_PAYLOAD = "QUICK_QUOTE_PAYLOAD";
export const QUICK_QUOTE_RESULTS = "QUICK_QUOTE_RESULTS";
export const SELECTED_PLAN = "SELECTED_PLAN";

export const RESET_QUICK_QUOTE_PAYLOAD = "RESET_QUICK_QUOTE_PAYLOAD";
export const RESET_QUICK_QUOTE_RESULTS = "RESET_QUICK_QUOTE_RESULTS";
export const RESET_SELECTED_PLAN = "RESET_SELECTED_PLAN";
